Fix handling of successfully merged encrypted files
Fix transcrypt's handling of merges where encrypted
files are successfully merged by git's `merge-file`
and can be automatically merged.

Previously this situation would fail with:

    error: add_cacheinfo failed to refresh for path 'FILE'; merge aborting.

The root problem is a subtle transcrypt requirement
that a decrypted file have both the correct file
name and up-to-date plaintext contents to generate
a valid HMAC salt value.

Making these two things align during the merge
process requires a surprising amount of juggling.